#openAPI definition
openapi: 3.0.0

info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

# Enable access to all API paths relative to localhost
servers:
  - url: "/api"

# Define API endpoints
paths:
  # Relative url of api endpoint
  /people:
    # HTTP method that endpoint responds to
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"